version: '2.38.2'

services:

  backend:
    build: backend
    context: ./backend
    dockerfile: Dockerfile-backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - ares-network

  frontend:
    build: frontend
    context: ./frontend
    dockerfile: Dockerfile-frontend
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:8000/api
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - ares-network

networks:
  ares-network: {}